spring:
  application:
    name: document-service

  # Activer Flyway pour ce service
  flyway:
    enabled: true
    schemas: document
    default-schema: document

# Port sp√©cifique pour ce service
server:
  port: 8085
