spring:
  application:
    name: migration-service

  # Configuration Flyway pour les migrations (uniquement dans ce service)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: true

# Port spécifique pour ce service
server:
  port: 8081

# Logging spécifique pour les migrations
logging:
  level:
    org.flywaydb: INFO
