spring:
  application:
    name: notification-service

  # Activer Flyway pour ce service
  flyway:
    enabled: true
    schemas: notification
    default-schema: notification

# Port sp√©cifique pour ce service
server:
  port: 8086
