spring:
  application:
    name: auth-service

  # Activer Flyway pour ce service
  flyway:
    enabled: true
    schemas: auth
    default-schema: auth

# Port sp√©cifique pour ce service
server:
  port: 8083
