spring:
  application:
    name: accounting-service

  # Configuration PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/compta
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # Activer Flyway pour ce service
  flyway:
    enabled: true
    schemas: accounting
    default-schema: accounting

# Port sp√©cifique pour ce service
server:
  port: 8082
