spring:
  application:
    name: accounting-service

  # Activer Flyway pour ce service
  flyway:
    enabled: true
    schemas: accounting
    default-schema: accounting

# Port sp√©cifique pour ce service
server:
  port: 8082
