spring:
  application:
    name: hr-service

  # Activer Flyway pour ce service
  flyway:
    enabled: true
    schemas: hr
    default-schema: hr

# Port sp√©cifique pour ce service
server:
  port: 8084
